### ISSUE TITLE
Error while using Wifite

### ISSUE THREAD

**Issue by twhp-electronic** [seppzer0/zero_kernel#6]
Installed (meanwhile 3 times and still get this errors):
Lineage 
Kernel (zero-0.4.1...x4.4)
Magisk
DM-Verity and Force Disabler
After Config oft the system: Nethunter

With and without updates: if I start Wifite I get the errors attached as screenshot

![Screenshot_20240226-161759_NetHunter Terminal](https://github.com/seppzer0/zero_kernel/assets/81389710/becce76e-376c-4a33-a57c-b4fb6228dc7a)
![Screenshot_20240226-161807_NetHunter Terminal](https://github.com/seppzer0/zero_kernel/assets/81389710/e97e5b94-5440-4bcc-9c09-27a41c0bfbf8)

**Comment by seppzer0** [comment]
That's odd. LineageOS+Magisk configuration should be the least problematic one.
I'll look into it.

**Comment by seppzer0** [comment]
I have just installed the LineageOS+Magisk configuration in my device and I'm encountering no issues whatsoever.

- Have you followed these [instructions](https://github.com/seppzer0/zero_kernel/blob/main/docs/FLASHING.md)?
- And also, -- could you also describe how exactly you are launching wifite?

**Comment by twhp-electronic** [comment]
First question:
I followed the instructions and hope that I installed everything the right way...

- first installed lineage
- as Kernel I used zero-0.4.1-dumplinger-x-4.4
- as Magisk I used Magisk.v26.3 and updated it
- and I used Disable_Dm-Verity_ForceEncrypt_11.02.2020

after that: boot to the system -> config -> reboot and install Nethunter...


Second question: I start it out of Nethunter by choosing "Custom commands" -> Launch Wifite...
Nethunter and Terminal are at the present version.

Already had the problem in the last release when the zero kernel came out the first time...
First thought that the problem would be that I used the official Lineage Release from the website... but it doesn't make a difference if I use your build or the official one - same problem.

It also doesn't make a difference if I use the internal Wifi module or an external

**Comment by seppzer0** [comment]
@twhp-electronic ,

> after that: boot to the system -> config (active USB debugging, swap sensorkeys, activate USB-Debugging and expanded reboot) -> reboot and install Nethunter...

Based on what you listed here, you are missing the steps that require finishing the Magisk installation in your system.
Please re-read the instructions carefully and follow each step through (take notice of the first two steps [here](https://github.com/seppzer0/zero_kernel/blob/main/docs/FLASHING.md#for-magisk-users)).
I have used these instructions myself when switching to the LineageOS+Magisk setup, and everything works just fine.


> I start it out of Nethunter by choosing "Custom commands" -> Launch Wifite...

I tested this approach myself -- it works for me, which means that the issue is not here.


> that I used the official Lineage Release from the website... but it doesn't make a difference if I use your build or the official latest one

Correct, there would be no difference. As I mentioned, the issue is likely in your Magisk installation process.

--
Also, let me know which versions of NetHunter apps you are using.
Some of the old versions had similar issues with apps crashing, so downloading the currently newest ones is recommended.
Here are the [links](https://github.com/seppzer0/zero_kernel/blob/16875d6ee0dfd67fcb7495cb3d0352d9ae0a5228/wrapper/core/assets_collector.py#L84C17-L87C69) to get the latest .apk files.

Let me know if you are able to get your NetHunter working.

**Comment by twhp-electronic** [comment]
Didn't write it... but made the finishing of the Magisk installation...

Well... I can't tell why this problem appears then... will have a look, at
your link then.

Best regards
Tobias

Am Mi., 6. März 2024 um 17:40 Uhr schrieb Joseph P ***@***.***

**Comment by twhp-electronic** [comment]
Updated all apks.
The error happens now a lot less... Still got it one time trying 6 times now.
But with that I can live! Thank you!

**Comment by seppzer0** [comment]
I'm still unsure why the error could happen.
But it's good to hear it is less of a problem now!
